4/bael/config/routes.rb
IDo::Application.routes.draw do

  resources :bonus_achievements
  
  devise_for :users, :path_prefix => 'd', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  

  
  root :to => 'application#index', :as => :home
  match 'select' => 'activities#select', :as => :activities_select
  match 'submit' => 'activities#submit', :as => :activities_submit
  match 'my_achievements' => 'achievements#user_achievements', :as => :my_achievements
  resources :achievements
  resources :activities

  match 'register' => 'user#register'
  match 'new_user' => 'user#new_user'

end

4/bael/app/models/achievement.rb
class Achievement < ActiveRecord::Base
  attr_accessible :description, :name, :picture_url, :duration, :count, :activity_id
  belongs_to :activity, :class_name=>'Activity'
  has_many :users, :class_name=>'UserAchievement', :foreign_key=>'achievement_id'
  
  def user_has_gained(user_id, finish_time)
    return false if activity_id.nil? 
    start_time = finish_time - (60 * 60 * 24 * duration)
    if duration == 0
      start_time = 0
      finish_time = 0
    end
    return Globals.get_activities_count_by_user_and_range(user_id, activity_id, start_time, finish_time) >= count
  end
  
  def self.create_achievements_by_user_id_and_activity_id(user_id, activity_id, finish_time)
    Achievement.find_all_by_activity_id(activity_id).each { |achievement| 
      if achievement.user_has_gained(user_id, finish_time)
        if UserAchievement.find_all_by_user_id_and_achievement_id(user_id, achievement.id).first.nil?  
          UserAchievement.create(:user_id => user_id,  :achievement_id => achievement.id)
          Achievement.create_user_bonuses(user_id)
        end  
      end
    }
  
  end

  def self.get_by_user(user_id)
    UserAchievement.find_all_by_user_id(user_id).to_a.collect{ |ua| ua.achievement}
  end
  
  # adding additional achievements
  def self.create_user_bonuses(user_id)
    user = User.find(user_id)
    return if user.nil?
    ids = []
    UserAchievement.find_all_by_user_id(user_id).each {|user_achievement | ids.push(user_achievement.achievement_id) }
    
    bonuses_ids = []
    Globals.calc_bonuses_ids(ids.sort, bonuses_ids)
    
    
    bonuses_ids.each { |id| 
      UserAchievement.create(:user_id => user_id, :achievement_id => id) if UserAchievement.find_all_by_user_id_and_achievement_id(user_id, id).first.nil? }
  end
  
  def self.init_bonus_achievements(bonus_id, ids)
    Globals.init_bonus_achievements(bonus_id, ids.sort)
  end
  
end

4/bael/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

  before_filter :is_admin?
  
  def user_achievements
    @achievements = Achievement.get_by_user(current_user.id)
  end

  # GET /achievements
  # GET /achievements.json
  def index
    @achievements = Achievement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @achievements }
    end
  end

  # GET /achievements/1
  # GET /achievements/1.json
  def show
    @achievement = Achievement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @achievement }
    end
  end

  # GET /achievements/new
  # GET /achievements/new.json
  def new
    @achievement = Achievement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @achievement }
    end
  end

  # GET /achievements/1/edit
  def edit
    @achievement = Achievement.find(params[:id])
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(params[:achievement])

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to @achievement, :notice => 'Achievement was successfully created.' }
        format.json { render :json => @achievement, :status => :created, :location => @achievement }
      else
        format.html { render :action => "new" }
        format.json { render :json => @achievement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /achievements/1
  # PUT /achievements/1.json
  def update
    @achievement = Achievement.find(params[:id])

    respond_to do |format|
      if @achievement.update_attributes(params[:achievement])
        format.html { redirect_to @achievement, :notice => 'Achievement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @achievement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement = Achievement.find(params[:id])
    @achievement.destroy

    respond_to do |format|
      format.html { redirect_to achievements_url }
      format.json { head :no_content }
    end
  end
end

4/bael/app/helpers/achievements_helper.rb
module AchievementsHelper
  def achievements
    if current_user.nil?
      []
    else
      Achievement.get_by_user(current_user.id)
    end
  end
end

4/bael/app/views/achievements/_form.html.erb
<%= form_for(@achievement) do |f| %>
  <% if @achievement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@achievement.errors.count, "error") %> prohibited this achievement from being saved:</h2>

      <ul>
      <% @achievement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>

  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>

  <div class="field">
  <%= f.label :activity_id %><br />
  <div class='input'>
      <%= select "achievement", "activity_id", Activity.all.collect {|p| [ p.name, p.id ] }, :include_blank => true %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

4/bael/app/views/achievements/_user_achievements.html.erb
<% unless @user.nil? %>
  <h2>Achievements</h2>
  <div class="well" style="overflow: auto;">
    <% if @user.achievements.empty? %>
      <h4>You currently have no achievements.</h4>
      <h4>Why don't you submit your activity?</h4>
    <% else %>
      <% @user.achievements.each do |a| %>
        <div class='achievement-container' title="<%= a.name %>" rel="popover" data-content="<%= a.description %>" data-original-title="<%= a.name %>">
          <img src="/images/achievements/<%= a.picture_url %>" alt="<%= a.description %>">
          <p><%= a.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  $(function () {
    $(".achievement-container").popover();
  });

</script>

4/bael/app/views/achievements/edit.html.erb
<h1>Editing achievement</h1>

<%= render 'form' %>

<%= link_to 'Show', @achievement %> |
<%= link_to 'Back', achievements_path %>

4/bael/app/views/achievements/index.html.erb
<h1>Listing achievements</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Activity</th>
    <th>Duration</th>
    <th>Count</th>
    <th></th>
  </tr>

<% @achievements.each do |achievement| %>
  <tr>
    <td><%= achievement.name %></td>
    <td><%= achievement.description %></td>
    <td><%= achievement.activity.name unless achievement.activity.nil? %></td>
    <td><%= achievement.duration %></td>
    <td><%= achievement.count %></td>
    <td><%= link_to 'Show', achievement %></td>
    <td><%= link_to 'Edit', edit_achievement_path(achievement) %></td>
    <td><%= link_to 'Destroy', achievement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Achievement', new_achievement_path %>

4/bael/app/views/achievements/new.html.erb
<h1>New achievement</h1>

<%= render 'form' %>

<%= link_to 'Back', achievements_path %>

4/bael/app/views/achievements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @achievement.name %>
</p>

<p>
  <b>Description:</b>
  <%= @achievement.description %>
</p>

<p>
  <b>Activity:</b>
  <%= @achievement.activity.name unless @achievement.activity.nil? %>
</p>

<p>
  <b>Duration:</b>
  <%= @achievement.duration %>
</p>

<p>
  <b>Count:</b>
  <%= @achievement.count %>
</p>


<%= link_to 'Edit', edit_achievement_path(@achievement) %> |
<%= link_to 'Back', achievements_path %>