4/bael/config/routes.rb
IDo::Application.routes.draw do

  resources :bonus_achievements
  
  devise_for :users, :path_prefix => 'd', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  

  
  root :to => 'application#index', :as => :home
  match 'select' => 'activities#select', :as => :activities_select
  match 'submit' => 'activities#submit', :as => :activities_submit
  match 'my_achievements' => 'achievements#user_achievements', :as => :my_achievements
  resources :achievements
  resources :activities

  match 'register' => 'user#register'
  match 'new_user' => 'user#new_user'

end

4/bael/app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :parent_id, :duration, :picture_url
  belongs_to :parent, :class_name=>'Activity'
  has_many :children, :class_name=>'Activity', :foreign_key=>'parent_id'
end

4/bael/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  
  before_filter :is_admin?, :except=>[:submit]
  
  def select
  end

  def submit
    user_id = current_user.id
    activity_id = params[:activity_id]

    duration = params[:duration]
    unless activity_id.to_i.to_s == activity_id
      duration = 5
    end

    finish_time = Time.new.to_i+(duration.to_i*60)
    Globals.save_activity(user_id, activity_id, finish_time)
    Achievement.create_achievements_by_user_id_and_activity_id(user_id, activity_id, finish_time)
    
    redirect_to home_url
  end

  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @activities }
    end
  end

  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @activity }
    end
  end

  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @activity }
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, :notice => 'Activity was successfully created.' }
        format.json { render :json => @activity, :status => :created, :location => @activity }
      else
        format.html { render :action => "new" }
        format.json { render :json => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, :notice => 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

4/bael/app/helpers/activities_helper.rb
module ActivitiesHelper
  def activities
    Activity.all.collect{|a| [a.name, a.id]}
  end
  
  def activities_list
    #Activity.all.collect{|a| {:id=>a.id,:name=>a.name,:duration=>a.duration}}
    Activity.all
  end

  def recent_user_activities
    Globals.recent_activities(20).collect{|ra|
      {:user_id => ra[:user_id], :user_name => User.find(ra[:user_id]).name,
       :user_picture => User.find(ra[:user_id]).image_url, :activity_id => ra[:activity_id] }
    }
  end

  def users_doing_the_same(activity_id)
    Globals.get_users_doing_the_same(activity_id).collect{|ra|
      {:user_id => ra, :user_name => User.find(ra).name,
       :user_picture => User.find(ra).image_url, :activity_id => activity_id }
    }
  end
  
  def last_user_activities(user,count)
    Globals.last_user_activities(user.id, count).collect{|ra|
       {:user_id => user.id, :user_name => user.name,
       :user_picture => user.image_url, :activity_id => ra[:activity_id], :start_time => ra[:start_time], :finish_time => ra[:finish_time]}
    }
  end
  
  def activity_of_current_user
    activity_of_user current_user
  end
  
  def activity_of_user(user)
    Globals.get_user_current_activity(user.id)
  end
end

4/bael/app/views/activities/_activity_with_picture.html.erb
<% activity = Activity.find(activity_id) %>
<span class="activity-container">
  <img src="/images/activities/<%= activity.picture_url %>" alt="<%= activity.name %>" />
  <%= activity.name %>
</span>

4/bael/app/views/activities/_current_user_activity.html.erb
<% unless @user.nil? %>
  <h2><%= @user==current_user ? 'Your' : @user.name %> current activity</h2>
  <div class='well'>
    <% current_activity_id = activity_of_user @user%>
    <% if current_activity_id.blank? %>
      <b>Why not submit some activity?</b>
    <% else %>
      <b></b><%= render :partial => 'activities/activity_with_picture', :locals => {:activity_id => current_activity_id} %>
    <% end %>
  </div>
<% end %>

4/bael/app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>

  <div class="field">
  <%= f.label :parent_id %><br />
  <div class='input'>
      <%= select "activity", "parent_id", Activity.all.collect {|p| [ p.name, p.id ] }, :include_blank => true %>
  </div>


  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

4/bael/app/views/activities/_recent_activities.html.erb
<h2>Recent activities</h2>

<ul class="unstyled activity-list">
  <% if activity_of_current_user.blank? %>
    <% 
		activities = recent_user_activities 
	%>
  <% else %>
    <% 
		activities = users_doing_the_same(activity_of_current_user)
		act_time = "ACT TIME"
	%>
  <% end %>
  <% activities.each do |ra| %>
	  <li>
		<img src="<%= ra[:user_picture] %>" alt="<%= ra[:user_name] %>" style="width:30px;height:30px" />
		<span><%= link_to ra[:user_name], user_path(ra[:user_id]) %></span>
		<%= render :partial => 'activities/activity_with_picture', :locals => {:activity_id => ra[:activity_id]} %>
		<%= act_time %>
	  </li>
  <% end %>
</ul>

4/bael/app/views/activities/_same_activities.html.erb
<% activities = users_doing_the_same(activity_of_current_user) %>

<h2><%= activities.size > 1 ? "#{activities.size} people are" : "1 person is" %> doing the same</h2>

<ul class="unstyled activity-list">
  

  <% activities.each do |ra| %>
  <li>
    <img src="<%= ra[:user_picture] %>" alt="<%= ra[:user_name] %>" style="width:30px;height:30px" />
    <span><%= link_to ra[:user_name], user_path(ra[:user_id]) %></span>
    <%= render :partial => 'activities/activity_with_picture', :locals => {:activity_id => ra[:activity_id]} %>
  </li>
  <% end %>
</ul>

4/bael/app/views/activities/_select_activity.html.erb
<style>
	#div.slider_block { padding: 10px !important; }
	</style>
	<script>
    var objArray = new Array();
  
    
    <% activities_list.each do |act| %>
			<% if(act.duration!=nil)%>
				objArray[<%= act.id %>] = <%=  act.duration.to_int %>;
			<% end %>
    <% end %>
    
    $(function() {
        $( "#slider" ).slider({
          value:0,
          min: 5,
          max: 60,
          step: 5,
          slide: function( event, ui ) {
            $("#duration_label").text( ui.value  + " min");
            $("#duration_input").val(ui.value);
          }
        });
        $("#duration_label").text( $( "#slider" ).slider( "value" ) + " min" );
        $("#duration_input").val($( "#slider" ).slider( "value" ));
      });
	  
	  $("#duration").filter_input({regex:'[0-9]',live:true});
	</script>

<div class='well' style="padding: 10px 0 1px 10px;width: 470px;">

  <%= form_tag activities_submit_url, :method => 'post', :style => 'margin:0;padding:0' do %>
    <%= select_tag(:activity_id, options_for_select(activities), :id => 'select-activity') %>
    <div id="image-container" style="margin: 0 3px;width: 25px;display: inline-block;"></div>
    <div id="slider" style="display: inline-block;width: 50px;margin: 0 5px;"></div>
    <%= hidden_field_tag :duration,'5', :id => 'duration_input' %>
    <div style="width: 50px;display: inline-block;"><span id="duration_label" style="font-weight:bold;width: 50px">Trololo</span></div>
    <%= submit_tag 'Submit', :class => 'btn btn-primary btn-large', :style => 'margin-bottom: 10px;' %>
  <% end %>
</div>

<script type="text/javascript">
  $("#select-activity").change(function () {
    var name = $("#select-activity option:selected").text().replace(/ /g,"_");
    var id = $("#select-activity option:selected").attr("value");
	
	if (objArray[id]!=undefined)
	{
		$("#slider").slider( "value" ,objArray[id]);
		$("#duration").attr( "value" ,objArray[id]);
	}
    $("#image-container").empty();
    $("#image-container").append('<img style="padding-bottom: 8px;" src="/images/activities/' + name + '.png"></img>');
  }).trigger('change');
</script>

4/bael/app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

4/bael/app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= activity.duration %></td>
    <td><%= activity.parent_id %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

4/bael/app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

4/bael/app/views/activities/select.html.erb
<h2>What are you doing right now?</h2>
<%= render 'select_activity' %>

4/bael/app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>

<p>
  <b>Duration:</b>
  <%= @activity.duration %>
</p>

<p>
  <b>Parent:</b>
  <%= @activity.parent_id %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>