4/bael/config/routes.rb
IDo::Application.routes.draw do

  resources :bonus_achievements
  
  devise_for :users, :path_prefix => 'd', :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  

  
  root :to => 'application#index', :as => :home
  match 'select' => 'activities#select', :as => :activities_select
  match 'submit' => 'activities#submit', :as => :activities_submit
  match 'my_achievements' => 'achievements#user_achievements', :as => :my_achievements
  resources :achievements
  resources :activities

  match 'register' => 'user#register'
  match 'new_user' => 'user#new_user'

end

4/bael/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>iDo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <style>
    body {
      padding-top: 60px;
    }
  </style>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'iDo', home_url, :class => 'brand' %>
          <div class="nav-collapse">
            
            <p class="navbar-text pull-right" style="width: 295px;">
              <%= authorisation_html %>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="top-section">
        <h1>Share activities. Gain achievements</h1>
      </div>

      <div class="row show-grid">
        <div class="span8">
          <%= yield %>
        </div>

        <div class="span4">
          <%= render :partial => 'activities/current_user_activity', :locals=>{:user=>@user} %>
          <%= render :partial => 'achievements/user_achievements', :locals=>{:user=>@user} %>
        </div>
      </div>
    </div>
</body>
</html>

4/bael/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>iDo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <style>
    body {
      padding-top: 60px;
    }
  </style>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'iDo', home_url, :class => 'brand' %>
        
        </div>
      </div>
    </div>

    <div class="container">
      <div class="top-section">
        <h1>Share activities. Gain achievements</h1>
      </div>

      <div class="row show-grid">
        <div class="span8">
          <%= yield %>
        </div>

      </div>
    </div>
</body>
</html>